const stableSymbols = {
    "FTX": ["LUNA", "LUNC", "LUNA2"],
    "APECOIN": ["APE"],
    "ALCHEMY PAY": ["ACH"],
    "ZKSYNC": ["ZK"],
    "PHALA": ["PHA"],
    "POLYMESH": ["POLYX"],
    "CZ": ["BNB"],
    "VECHAIN": ["VET"],
    "IMMUTABLE": ["IMX"],
    "ELON MUSK": ["PNUT", "DOGE", "BANANA"],
    "DO KWON": ["LUNC", "LUNA2", "LUNA", "USTC"],
    "ADVENTURE GOLD": ["AGLD"],
    "AIRDAO": ["AMB"],
    "APTOS": ["APT"],
    "ARBITRUM": ["ARB"],
    "ARKHAM": ["ARKM"],
    "AUDIUS": ["AUDIO"],
    "AVALANCHE": ["AVAX"],
    "AXELAR": ["AXL"],
    "AXIE INFINITY": ["AXS"],
    "BICONOMY": ["BICO"],
    "BINANCE": ["BNB"],
    "CHILIZ": ["CHZ"],
    "CHROMIA": ["CHR"],
    "CURVE": ["CRV"],
    "CARTESI": ["CTSI"],
    "CIVIC": ["CVC"],
    "ETHENA": ["ENA"],
    "ENJIN": ["ENJ"],
    "ETHEREUM CLASSIC": ["ETC"],
    "ETHEREUM": ["ETH"],
    "GRAVITY": ["G"],
    "FLAMINGO": ["FLM"],
    "FANTOM": ["FTM"],
    "STEPN": ["GMT"],
    "HEDERA": ["HBAR"],
    "HAMSTER": ["HMSTR"],
    "HELIUM": ["HNT"],
    "SPACE ID": ["ID"],
    "INJECTIVE": ["INJ"],
    "JITO": ["JTO"],
    "JUPITER": ["JUP"],
    "KASPA": ["KAS"],
    "SELFKEY": ["KEY"],
    "KYBER NETWORK": ["KNC"],
    "KUSAMA": ["KSM"],
    "LIDO": ["LDO"],
    "LINEAR": ["LINA"],
    "CHAINLINK": ["LINK"],
    "LIVEPEER": ["LPT"],
    "LISK": ["LSK"],
    "LOOPRING": ["LRC"],
    "LITECOIN": ["LTC"],
    "METAMASK": ["MASK"],
    "MANTLE": ["MNT"],
    "IGGY AZALEA": ["MOTHER"],
    "METAL DAO": ["MTL"],
    "ONTOLOGY": ["ONT"],
    "OPTIMISM": ["OP"],
    "BENQI": ["QI"],
    "RAYDIUM": ["RAY"],
    "RONIN": ["RON"],
    "SIACOIN": ["SC"],
    "SAFEPAL": ["SFP"],
    "SHIBA INU": ["SHIB", "1000SHIB", "SHIB1000"],
    "SANDBOX": ["SAND"],
    "SOLANA": ["SOL"],
    "STARKNET": ["STRK"],
    "SUNPUMP": ["SUN"],
    "SUSHISWAP": ["SUSHI"],
    "BITTENSOR": ["TAO"],
    "CELESTIA": ["TIA"],
    "TELEGRAM": ["TON"],
    "DUROV": ["TON"],
    "TELLOR": ["TRB"],
    "TRUEFI": ["TRU"],
    "TRON": ["TRX"],
    "TRUST WALLET": ["TWT"],
    "UNISWAP": ["UNI"],
    "HAYDEN ADAMS": ["UNI"],
    "WORLDCOIN": ["WLD"],
    "WORMHOLE": ["W"],
    "STELLAR": ["XLM"],
    "TEZOS": ["XTZ"],
    "RIPPLE": ["XRP"],
    "ZCASH": ["ZEC"],
    "ZILLIQA": ["ZIL"]
  }
  
  module.exports = {stableSymbols}